### ISSUE TITLE
update the README.md

### ISSUE THREAD

**Issue by DeltaNicola** [DeltaNicola/automic_flow#4]

**Comment by DeltaNicola** [comment]
- [ ] explaining the gui #1 
- [ ] explaining the creation #2 
- [ ] explaining the cloning #3
